// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// doi_parse
std::string doi_parse(std::string x);
RcppExport SEXP _parseids_doi_parse(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(doi_parse(x));
    return rcpp_result_gen;
END_RCPP
}
// doi_parse_many
CharacterVector doi_parse_many(CharacterVector x);
RcppExport SEXP _parseids_doi_parse_many(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(doi_parse_many(x));
    return rcpp_result_gen;
END_RCPP
}
// replace_all_symbols
std::string replace_all_symbols(std::string x);
RcppExport SEXP _parseids_replace_all_symbols(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(replace_all_symbols(x));
    return rcpp_result_gen;
END_RCPP
}
// replace_specific_symbols
std::string replace_specific_symbols(std::string const& x);
RcppExport SEXP _parseids_replace_specific_symbols(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string const& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(replace_specific_symbols(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_parseids_doi_parse", (DL_FUNC) &_parseids_doi_parse, 1},
    {"_parseids_doi_parse_many", (DL_FUNC) &_parseids_doi_parse_many, 1},
    {"_parseids_replace_all_symbols", (DL_FUNC) &_parseids_replace_all_symbols, 1},
    {"_parseids_replace_specific_symbols", (DL_FUNC) &_parseids_replace_specific_symbols, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_parseids(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
