# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doi_parse <- function(x) {
    .Call('_parseids_doi_parse', PACKAGE = 'parseids', x)
}

doi_parse_many <- function(x) {
    .Call('_parseids_doi_parse_many', PACKAGE = 'parseids', x)
}

replace_all_symbols <- function(x) {
    .Call('_parseids_replace_all_symbols', PACKAGE = 'parseids', x)
}

replace_specific_symbols <- function(x) {
    .Call('_parseids_replace_specific_symbols', PACKAGE = 'parseids', x)
}

